

/*
Exception (try - catch - throw) mantığını daha iyi 
anlamak için güzel bir örnek yap
*/

#include <iostream>




int main(void)
{

    int  resutl = 6 / 0;    // anlamsız olur
    std::cout << resutl << std::endl;

    
    return 0;
}




